# the language
lang: en
# author info
author:
  name: Haroen Viaene
  email: hello@haroen.me
  twitter: '@haroenv'
# title and description
title: Visit Gent
description: Search what you can do in Ghent
# the url this will be published at
url: https://haroen.me
baseurl: /visit-gent
# the theme colour
color:
# location of some files
css: ['/src/style.css']
scripts: ['/src/bundle.js']
favicon: ['../apple-touch-icon.png']
#configuration
sass:
  style: compressed
